OBJECTS = 9_4.exe 9_5.exe 9_18.exe 9_20.exe 9_22.exe 9_27.exe seq_container.exe \
		  9_31.exe 9_41.exe 9_44.exe 9_47.exe 9_51.exe 9_52.exe

include ../GNU_makefile_template

# LOCFLAGS = -I../7
# 
# fio.exe: fio.o ../7/scales_data.o
# 	$(CC) $(CCFLAGS) $(LOCFLAGS) fio.o ../7/scales_data.o -o fio.exe


